FROM golang:1.14.3-alpine3.11 as builder

RUN apk update && \
    apk add --no-cache git ca-certificates && \
    update-ca-certificates

ENV USER=appuser
ENV UID=10001

RUN adduser \    
    --disabled-password \    
    --gecos "" \    
    --home "/nonexistent" \    
    --shell "/sbin/nologin" \    
    --no-create-home \    
    --uid "${UID}" \    
    "${USER}"

FROM alpine

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

ADD greeter /usr/bin/greeter
USER appuser:appuser

EXPOSE 8080

ENTRYPOINT ["/usr/bin/greeter"]
