apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    email: me@ch4z.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-dev-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
